### ISSUE TITLE
Can you tell me which paper CGGMM-IVA comes from?

### ISSUE THREAD

**Issue by makabakas** [shelly-tang/CGGMM-IVA#1]

**Comment by shelly-tang** [comment]
Hi, makabakas. CGGMM-IVA is proposed in paper: Xinyu Tang, Rilin Chen, Xiyuan Wang, Yi Zhou and Su Dan. "Independent vector analysis for blind speech separation using complex generalized gaussian mixture model with weighted variance". It was presented in APSIPA 2020 last week and still in press now.

**Comment by makabakas** [comment]
Thank you for your answer, this algorithm looks like an offline algorithm...

**Comment by shelly-tang** [comment]
Yes, the demo is processed by offline algorithm. I have not  implemented the online version.
